## After runing the make_prediction.sh 4 times:
(.devops) /AWS_Projects/py_local_env/ml-microservice-kubernetes$ ./make_prediction.sh
Port: 8000
{
  "prediction": [
    20.35373177134412
  ]
}
(.devops) /AWS_Projects/py_local_env/ml-microservice-kubernetes$ ./make_prediction.sh
Port: 8000
{
  "prediction": [
    20.35373177134412
  ]
}
(.devops) /AWS_Projects/py_local_env/ml-microservice-kubernetes$ ./make_prediction.sh
Port: 8000
{
  "prediction": [
    20.35373177134412
  ]
}
(.devops) /AWS_Projects/py_local_env/ml-microservice-kubernetes$ ./make_prediction.sh 
Port: 8000
{
  "prediction": [    
    20.35373177134412
  ]
}

## the out put for kubernetes cluster is:
(.devops) /AWS_Projects/py_local_env/ml-microservice-kubernetes$ ./run_kubernetes.sh
Error from server (AlreadyExists): pods "mlmicroserviceapi" already exists
NAME                READY   STATUS    RESTARTS   AGE
mlmicroserviceapi   1/1     Running   0          6m18s
Forwarding from 127.0.0.1:8000 -> 80
Forwarding from [::1]:8000 -> 80
Handling connection for 8000
Handling connection for 8000
Handling connection for 8000
Handling connection for 8000
